version: '3.3'
services:

  solution:
    volumes:  
      - '..:/app'
    container_name: solution
    image: microsoft/dotnet:2.2-sdk
    working_dir: /app/csharp
    entrypoint: /bin/bash -c "dotnet run --project solution/csharp.csproj"

  unit-tests:
    volumes:
      - '..:/app'
    container_name: unit-tests
    image: microsoft/dotnet:2.2-sdk
    working_dir: /app/csharp
    entrypoint: /bin/bash -c "dotnet test"
